export interface ProduceListing {
  id: string;
  cropType: string;
  variety: string;
  farmName: string;
  farmerName: string;
  region: string;
  state: string;
  grade: 'A+' | 'A' | 'B' | 'C';
  qualityScore: number;
  quantityKg: number;
  pricePerKg: number;
  harvestDate: string;
  availableUntil: string;
  freshnessScore: number;
  status: 'active' | 'pending' | 'sold' | 'flash';
  isCooperative: boolean;
  hasBlockchain: boolean;
  isFlashSale: boolean;
  imageUrl: string;
  imageAlt: string;
  minOrderKg: number;
  farmerRating: number;
  farmerOrders: number;
  listedAt: number;
  isBuyRequest?: boolean;
}

export const INITIAL_LISTINGS: ProduceListing[] = [
  {
    id: 'listing-001',
    cropType: 'Tomato',
    variety: 'Hybrid F1 — Naveen',
    farmName: 'Ramesh Kumar Farm',
    farmerName: 'Ramesh Kumar',
    region: 'Nashik',
    state: 'Maharashtra',
    grade: 'A',
    qualityScore: 94,
    quantityKg: 2800,
    pricePerKg: 28,
    harvestDate: '03/05/2026',
    availableUntil: '12/05/2026',
    freshnessScore: 96,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1723234387588-756c4d1e3e1a',
    imageAlt: 'Fresh red tomatoes on vine in sunlight',
    minOrderKg: 100,
    farmerRating: 4.8,
    farmerOrders: 312,
    listedAt: 1746518400,
    isBuyRequest: false
  },
  {
    id: 'listing-002',
    cropType: 'Onion',
    variety: 'Nasik Red — Medium',
    farmName: 'Suresh Patel Farm',
    farmerName: 'Suresh Patel',
    region: 'Solapur',
    state: 'Maharashtra',
    grade: 'A',
    qualityScore: 91,
    quantityKg: 5200,
    pricePerKg: 22,
    harvestDate: '28/04/2026',
    availableUntil: '18/05/2026',
    freshnessScore: 88,
    status: 'active',
    isCooperative: true,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1728363333238-1ebfd8eaf995',
    imageAlt: 'Pile of red onions with papery skin',
    minOrderKg: 500,
    farmerRating: 4.6,
    farmerOrders: 198,
    listedAt: 1746432000,
    isBuyRequest: false
  },
  {
    id: 'listing-003',
    cropType: 'Spinach',
    variety: 'Palak — All Season',
    farmName: 'Anita Reddy Organics',
    farmerName: 'Anita Reddy',
    region: 'Chittoor',
    state: 'Andhra Pradesh',
    grade: 'A',
    qualityScore: 97,
    quantityKg: 380,
    pricePerKg: 45,
    harvestDate: '05/05/2026',
    availableUntil: '08/05/2026',
    freshnessScore: 99,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_12d80f805-1773092219586.png',
    imageAlt: 'Fresh green spinach leaves in bunch',
    minOrderKg: 20,
    farmerRating: 4.9,
    farmerOrders: 87,
    listedAt: 1746604800,
    isBuyRequest: false
  },
  {
    id: 'listing-004',
    cropType: 'Potato',
    variety: 'Kufri Jyoti — Grade 1',
    farmName: 'Vikram Singh Cold Farm',
    farmerName: 'Vikram Singh',
    region: 'Agra',
    state: 'Uttar Pradesh',
    grade: 'B',
    qualityScore: 78,
    quantityKg: 12000,
    pricePerKg: 18,
    harvestDate: '15/04/2026',
    availableUntil: '30/06/2026',
    freshnessScore: 82,
    status: 'active',
    isCooperative: true,
    hasBlockchain: false,
    isFlashSale: false,
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_1398448c4-1768159074106.png',
    imageAlt: 'Brown potatoes in burlap sack on wooden floor',
    minOrderKg: 1000,
    farmerRating: 4.4,
    farmerOrders: 445,
    listedAt: 1746345600,
    isBuyRequest: false
  },
  {
    id: 'listing-005',
    cropType: 'Cauliflower',
    variety: 'Snowball — Extra Large',
    farmName: 'Gurmeet Kaur Farm',
    farmerName: 'Gurmeet Kaur',
    region: 'Ludhiana',
    state: 'Punjab',
    grade: 'A',
    qualityScore: 89,
    quantityKg: 1600,
    pricePerKg: 35,
    harvestDate: '04/05/2026',
    availableUntil: '10/05/2026',
    freshnessScore: 93,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1704596931787-977e8fd53ef1',
    imageAlt: 'White cauliflower head with green leaves',
    minOrderKg: 100,
    farmerRating: 4.7,
    farmerOrders: 156,
    listedAt: 1746518400,
    isBuyRequest: false
  },
  {
    id: 'listing-006',
    cropType: 'Okra',
    variety: 'Arka Anamika — Tender',
    farmName: 'Murugan Farms',
    farmerName: 'S. Murugan',
    region: 'Coimbatore',
    state: 'Tamil Nadu',
    grade: 'A',
    qualityScore: 92,
    quantityKg: 620,
    pricePerKg: 52,
    harvestDate: '06/05/2026',
    availableUntil: '09/05/2026',
    freshnessScore: 97,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1696835537510-981fdb76321f',
    imageAlt: 'Fresh green okra pods arranged on cloth',
    minOrderKg: 50,
    farmerRating: 4.7,
    farmerOrders: 203,
    listedAt: 1746691200,
    isBuyRequest: false
  },
  {
    id: 'listing-007',
    cropType: 'Capsicum',
    variety: 'California Wonder — Mixed',
    farmName: 'Ranjit Polyhouse',
    farmerName: 'Ranjit Sharma',
    region: 'Pune',
    state: 'Maharashtra',
    grade: 'A',
    qualityScore: 96,
    quantityKg: 440,
    pricePerKg: 68,
    harvestDate: '05/05/2026',
    availableUntil: '11/05/2026',
    freshnessScore: 98,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1716434128604-e7bff11ec0a8',
    imageAlt: 'Colorful red yellow and green capsicum peppers',
    minOrderKg: 50,
    farmerRating: 4.9,
    farmerOrders: 128,
    listedAt: 1746604800,
    isBuyRequest: false
  },
  {
    id: 'listing-008',
    cropType: 'Brinjal',
    variety: 'Arka Shirish — Purple Long',
    farmName: 'Patel Vegetable Farm',
    farmerName: 'Dinesh Patel',
    region: 'Anand',
    state: 'Gujarat',
    grade: 'B',
    qualityScore: 74,
    quantityKg: 980,
    pricePerKg: 30,
    harvestDate: '02/05/2026',
    availableUntil: '09/05/2026',
    freshnessScore: 76,
    status: 'flash',
    isCooperative: false,
    hasBlockchain: false,
    isFlashSale: true,
    imageUrl: 'https://images.unsplash.com/photo-1714751569833-85bb703b1b91',
    imageAlt: 'Dark purple brinjal eggplants on market stall',
    minOrderKg: 100,
    farmerRating: 4.2,
    farmerOrders: 89,
    listedAt: 1746259200,
    isBuyRequest: false
  },
  {
    id: 'listing-009',
    cropType: 'Carrot',
    variety: 'Nantes — Premium',
    farmName: 'Himachal Agro Collective',
    farmerName: 'Deepa Thakur',
    region: 'Shimla',
    state: 'Himachal Pradesh',
    grade: 'A',
    qualityScore: 93,
    quantityKg: 2200,
    pricePerKg: 42,
    harvestDate: '01/05/2026',
    availableUntil: '20/05/2026',
    freshnessScore: 91,
    status: 'active',
    isCooperative: true,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1606355194341-10e4cf647387',
    imageAlt: 'Bunch of fresh orange carrots with green tops',
    minOrderKg: 200,
    farmerRating: 4.6,
    farmerOrders: 174,
    listedAt: 1746172800,
    isBuyRequest: false
  },
  {
    id: 'listing-010',
    cropType: 'Green Chilli',
    variety: 'Byadgi — Long Hot',
    farmName: 'Reddy Chilli Estate',
    farmerName: 'Venkat Reddy',
    region: 'Guntur',
    state: 'Andhra Pradesh',
    grade: 'A',
    qualityScore: 88,
    quantityKg: 750,
    pricePerKg: 58,
    harvestDate: '04/05/2026',
    availableUntil: '12/05/2026',
    freshnessScore: 94,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1648627743560-cd547111b443',
    imageAlt: 'Green chilli peppers in pile on burlap sack',
    minOrderKg: 50,
    farmerRating: 4.8,
    farmerOrders: 267,
    listedAt: 1746518400,
    isBuyRequest: false
  },
  {
    id: 'listing-buy-001',
    cropType: 'Wheat',
    variety: 'Lokwan Premium',
    farmName: 'Priya Merchants Procurement',
    farmerName: 'Priya Merchants',
    region: 'Mumbai Wholesale Hub',
    state: 'Maharashtra',
    grade: 'A',
    qualityScore: 92,
    quantityKg: 5000,
    pricePerKg: 26,
    harvestDate: 'Immediate',
    availableUntil: '30/06/2026',
    freshnessScore: 90,
    status: 'active',
    isCooperative: false,
    hasBlockchain: true,
    isFlashSale: false,
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b',
    imageAlt: 'Golden wheat grain under sunlight',
    minOrderKg: 500,
    farmerRating: 4.9,
    farmerOrders: 24,
    listedAt: 1746604800,
    isBuyRequest: true
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'ord-801',
    crop: 'Tomato (Grade A)',
    qty: 1500,
    partner: 'Ramesh Kumar',
    location: 'Nashik, MH',
    totalVal: 45000,
    status: 'dispatched',
    date: '06 May 2026',
    hasBlockchain: true,
    buyerPhone: '9823456780',
    sellerPhone: '9876543210'
  },
  {
    id: 'ord-802',
    crop: 'Potato (Grade B)',
    qty: 2500,
    partner: 'Gurpreet Singh',
    location: 'Jalandhar, PB',
    totalVal: 45000,
    status: 'pending',
    date: '07 May 2026',
    hasBlockchain: true,
    buyerPhone: '9823456780',
    sellerPhone: '9876543210'
  },
  {
    id: 'ord-803',
    crop: 'Onion (Grade A)',
    qty: 1200,
    partner: 'Balu Shinde',
    location: 'Lasalgaon, MH',
    totalVal: 28800,
    status: 'delivered',
    date: '01 May 2026',
    hasBlockchain: true,
    buyerPhone: '9823456780',
    sellerPhone: '9876543210'
  },
  {
    id: 'ord-901',
    crop: 'Tomato (Grade A)',
    qty: 1500,
    partner: 'Priya Merchants',
    location: 'Mumbai, MH',
    totalVal: 45000,
    status: 'dispatched',
    date: '06 May 2026',
    hasBlockchain: true,
    buyerPhone: '9823456780',
    sellerPhone: '9876543210'
  },
  {
    id: 'ord-902',
    crop: 'Capsicum (Grade A)',
    qty: 800,
    partner: 'FreshMart Retail',
    location: 'Pune, MH',
    totalVal: 44000,
    status: 'delivered',
    date: '28 Apr 2026',
    hasBlockchain: false,
    buyerPhone: '9823456780',
    sellerPhone: '9876543210'
  }
];
