export interface ProduceListing {
  id: string;
  cropType: string;
  variety: string;
  farmName: string;
  farmerName: string;
  region: string;
  state: string;
  grade: 'A' | 'B' | 'C' | 'D';
  qualityScore: number;
  quantityKg: number;
  pricePerKg: number;
  originalPricePerKg?: number;
  harvestDate: string;
  availableUntil: string;
  freshnessScore: number;
  status: 'active' | 'reserved' | 'sold' | 'flash';
  isCooperative: boolean;
  cooperativeSize?: number;
  hasBlockchain: boolean;
  isFlashSale: boolean;
  flashDiscount?: number;
  flashEndsAt?: string;
  imageUrl: string;
  imageAlt: string;
  certifications: string[];
  listedAt: number;
  minOrderKg: number;
  farmerRating: number;
  farmerOrders: number;
  isBuyRequest?: number | boolean;
}

export const allListings: ProduceListing[] = [
{
  id: 'listing-001',
  cropType: 'Tomato',
  variety: 'Hybrid F1 — Naveen',
  farmName: 'Ramesh Kumar Farm',
  farmerName: 'Ramesh Kumar',
  region: 'Nashik',
  state: 'Maharashtra',
  grade: 'A',
  qualityScore: 94,
  quantityKg: 2800,
  pricePerKg: 28,
  harvestDate: '03/05/2026',
  availableUntil: '12/05/2026',
  freshnessScore: 96,
  status: 'active',
  isCooperative: false,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1723234387588-756c4d1e3e1a",
  imageAlt: 'Fresh red tomatoes on vine in sunlight',
  certifications: ['APEDA', 'Organic India'],
  listedAt: 1746518400,
  minOrderKg: 100,
  farmerRating: 4.8,
  farmerOrders: 312
},
{
  id: 'listing-002',
  cropType: 'Onion',
  variety: 'Nasik Red — Medium',
  farmName: 'Suresh Patel Farm',
  farmerName: 'Suresh Patel',
  region: 'Solapur',
  state: 'Maharashtra',
  grade: 'A',
  qualityScore: 91,
  quantityKg: 5200,
  pricePerKg: 22,
  harvestDate: '28/04/2026',
  availableUntil: '18/05/2026',
  freshnessScore: 88,
  status: 'active',
  isCooperative: true,
  cooperativeSize: 6,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1728363333238-1ebfd8eaf995",
  imageAlt: 'Pile of red onions with papery skin',
  certifications: ['FSSAI Certified'],
  listedAt: 1746432000,
  minOrderKg: 500,
  farmerRating: 4.6,
  farmerOrders: 198
},
{
  id: 'listing-003',
  cropType: 'Spinach',
  variety: 'Palak — All Season',
  farmName: 'Anita Reddy Organics',
  farmerName: 'Anita Reddy',
  region: 'Chittoor',
  state: 'Andhra Pradesh',
  grade: 'A',
  qualityScore: 97,
  quantityKg: 380,
  pricePerKg: 45,
  harvestDate: '05/05/2026',
  availableUntil: '08/05/2026',
  freshnessScore: 99,
  status: 'active',
  isCooperative: false,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_12d80f805-1773092219586.png",
  imageAlt: 'Fresh green spinach leaves in bunch',
  certifications: ['Organic India', 'PGS-India'],
  listedAt: 1746604800,
  minOrderKg: 20,
  farmerRating: 4.9,
  farmerOrders: 87
},
{
  id: 'listing-004',
  cropType: 'Potato',
  variety: 'Kufri Jyoti — Grade 1',
  farmName: 'Vikram Singh Cold Farm',
  farmerName: 'Vikram Singh',
  region: 'Agra',
  state: 'Uttar Pradesh',
  grade: 'B',
  qualityScore: 78,
  quantityKg: 12000,
  pricePerKg: 18,
  harvestDate: '15/04/2026',
  availableUntil: '30/06/2026',
  freshnessScore: 82,
  status: 'active',
  isCooperative: true,
  cooperativeSize: 12,
  hasBlockchain: false,
  isFlashSale: false,
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_1398448c4-1768159074106.png",
  imageAlt: 'Brown potatoes in burlap sack on wooden floor',
  certifications: ['FSSAI Certified'],
  listedAt: 1746345600,
  minOrderKg: 1000,
  farmerRating: 4.4,
  farmerOrders: 445
},
{
  id: 'listing-005',
  cropType: 'Cauliflower',
  variety: 'Snowball — Extra Large',
  farmName: 'Gurmeet Kaur Farm',
  farmerName: 'Gurmeet Kaur',
  region: 'Ludhiana',
  state: 'Punjab',
  grade: 'A',
  qualityScore: 89,
  quantityKg: 1600,
  pricePerKg: 35,
  harvestDate: '04/05/2026',
  availableUntil: '10/05/2026',
  freshnessScore: 93,
  status: 'active',
  isCooperative: false,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1704596931787-977e8fd53ef1",
  imageAlt: 'White cauliflower head with green leaves',
  certifications: ['APEDA'],
  listedAt: 1746518400,
  minOrderKg: 100,
  farmerRating: 4.7,
  farmerOrders: 156
},
{
  id: 'listing-006',
  cropType: 'Okra',
  variety: 'Arka Anamika — Tender',
  farmName: 'Murugan Farms',
  farmerName: 'S. Murugan',
  region: 'Coimbatore',
  state: 'Tamil Nadu',
  grade: 'A',
  qualityScore: 92,
  quantityKg: 620,
  pricePerKg: 52,
  harvestDate: '06/05/2026',
  availableUntil: '09/05/2026',
  freshnessScore: 97,
  status: 'active',
  isCooperative: false,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1696835537510-981fdb76321f",
  imageAlt: 'Fresh green okra pods arranged on cloth',
  certifications: ['Organic India'],
  listedAt: 1746691200,
  minOrderKg: 50,
  farmerRating: 4.7,
  farmerOrders: 203
},
{
  id: 'listing-007',
  cropType: 'Capsicum',
  variety: 'California Wonder — Mixed',
  farmName: 'Ranjit Polyhouse',
  farmerName: 'Ranjit Sharma',
  region: 'Pune',
  state: 'Maharashtra',
  grade: 'A',
  qualityScore: 96,
  quantityKg: 440,
  pricePerKg: 68,
  harvestDate: '05/05/2026',
  availableUntil: '11/05/2026',
  freshnessScore: 98,
  status: 'active',
  isCooperative: false,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1716434128604-e7bff11ec0a8",
  imageAlt: 'Colorful red yellow and green capsicum peppers',
  certifications: ['GlobalGAP', 'APEDA'],
  listedAt: 1746604800,
  minOrderKg: 50,
  farmerRating: 4.9,
  farmerOrders: 128
},
{
  id: 'listing-008',
  cropType: 'Brinjal',
  variety: 'Arka Shirish — Purple Long',
  farmName: 'Patel Vegetable Farm',
  farmerName: 'Dinesh Patel',
  region: 'Anand',
  state: 'Gujarat',
  grade: 'B',
  qualityScore: 74,
  quantityKg: 980,
  pricePerKg: 30,
  harvestDate: '02/05/2026',
  availableUntil: '09/05/2026',
  freshnessScore: 76,
  status: 'flash',
  isCooperative: false,
  hasBlockchain: false,
  isFlashSale: true,
  flashDiscount: 30,
  flashEndsAt: '2026-05-08T18:00:00',
  originalPricePerKg: 43,
  imageUrl: "https://images.unsplash.com/photo-1714751569833-85bb703b1b91",
  imageAlt: 'Dark purple brinjal eggplants on market stall',
  certifications: ['FSSAI Certified'],
  listedAt: 1746259200,
  minOrderKg: 100,
  farmerRating: 4.2,
  farmerOrders: 89
},
{
  id: 'listing-009',
  cropType: 'Carrot',
  variety: 'Nantes — Premium',
  farmName: 'Himachal Agro Collective',
  farmerName: 'Deepa Thakur',
  region: 'Shimla',
  state: 'Himachal Pradesh',
  grade: 'A',
  qualityScore: 93,
  quantityKg: 2200,
  pricePerKg: 42,
  harvestDate: '01/05/2026',
  availableUntil: '20/05/2026',
  freshnessScore: 91,
  status: 'active',
  isCooperative: true,
  cooperativeSize: 8,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1606355194341-10e4cf647387",
  imageAlt: 'Bunch of fresh orange carrots with green tops',
  certifications: ['Organic India', 'APEDA'],
  listedAt: 1746172800,
  minOrderKg: 200,
  farmerRating: 4.6,
  farmerOrders: 174
},
{
  id: 'listing-010',
  cropType: 'Green Chilli',
  variety: 'Byadgi — Long Hot',
  farmName: 'Reddy Chilli Estate',
  farmerName: 'Venkat Reddy',
  region: 'Guntur',
  state: 'Andhra Pradesh',
  grade: 'A',
  qualityScore: 88,
  quantityKg: 750,
  pricePerKg: 58,
  harvestDate: '04/05/2026',
  availableUntil: '12/05/2026',
  freshnessScore: 94,
  status: 'active',
  isCooperative: false,
  hasBlockchain: true,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1648627743560-cd547111b443",
  imageAlt: 'Green chilli peppers in pile on burlap sack',
  certifications: ['APEDA', 'Spices Board'],
  listedAt: 1746518400,
  minOrderKg: 50,
  farmerRating: 4.8,
  farmerOrders: 267
},
{
  id: 'listing-011',
  cropType: 'Cabbage',
  variety: 'Golden Acre — Round Head',
  farmName: 'Nilgiri Hill Farms',
  farmerName: 'Priya Devi',
  region: 'Ooty',
  state: 'Tamil Nadu',
  grade: 'B',
  qualityScore: 81,
  quantityKg: 3400,
  pricePerKg: 20,
  harvestDate: '29/04/2026',
  availableUntil: '15/05/2026',
  freshnessScore: 84,
  status: 'reserved',
  isCooperative: true,
  cooperativeSize: 5,
  hasBlockchain: false,
  isFlashSale: false,
  imageUrl: "https://images.unsplash.com/photo-1621142471060-28370379785a",
  imageAlt: 'Green round cabbage heads stacked in field',
  certifications: ['FSSAI Certified'],
  listedAt: 1746086400,
  minOrderKg: 300,
  farmerRating: 4.5,
  farmerOrders: 321
},
{
  id: 'listing-012',
  cropType: 'Bitter Gourd',
  variety: 'Preethi — Hybrid',
  farmName: 'Kerala Organic Hub',
  farmerName: 'Arun Nair',
  region: 'Thrissur',
  state: 'Kerala',
  grade: 'C',
  qualityScore: 63,
  quantityKg: 290,
  pricePerKg: 38,
  harvestDate: '30/04/2026',
  availableUntil: '08/05/2026',
  freshnessScore: 68,
  status: 'flash',
  isCooperative: false,
  hasBlockchain: false,
  isFlashSale: true,
  flashDiscount: 25,
  flashEndsAt: '2026-05-07T22:00:00',
  originalPricePerKg: 51,
  imageUrl: "https://images.unsplash.com/photo-1719143227376-a6b0a400711c",
  imageAlt: 'Green bitter gourd vegetables on wooden surface',
  certifications: ['PGS-India'],
  listedAt: 1746000000,
  minOrderKg: 30,
  farmerRating: 4.1,
  farmerOrders: 56
}];